
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import Link from "next/link";

const esrsS1Data = [
    { esrsId: "S1-1", dr: "DR", paragraph: "Paragraph", relatedAr: "Related AR", name: "Name", dataType: "Data Type", status: "bg-green-500" },
    { esrsId: "S1-2", dr: "SBM-3", paragraph: "14", relatedAr: "AR 6-AR7", name: "All people in its own workforce who can be materially impacted by undertaking are included in scope of disclosure under ESRS 2", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-3", dr: "SBM-3", paragraph: "14 a", relatedAr: "", name: "Description of types of employees and non-employees in its own workforce subject to material impacts ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-4", dr: "SBM-3", paragraph: "14 b", relatedAr: "", name: "Material negative impacts occurrence (own workforce)", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-5", dr: "SBM-3", paragraph: "14 c", relatedAr: "", name: "Description of activities that result in positive impacts and types of employees and non-employees in its own workforce that are positively affected or could be positively affected ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-6", dr: "SBM-3", paragraph: "14 d", relatedAr: "", name: "Description of material risks and opportunities arising from impacts and dependencies on own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-7", dr: "SBM-3", paragraph: "14 e", relatedAr: "", name: "Description of material impacts on workers that may arise from transition plans for reducing negative impacts on environment and achieving greener and climate-neutral operations ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-8", dr: "SBM-3", paragraph: "14 f (i) ", relatedAr: "", name: "Information about type of operations at significant risk of incidents of forced labour or compulsory labour ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-9", dr: "SBM-3", paragraph: "14 f (ii) ", relatedAr: "", name: "Information about countries or geographic areas with operations considered at significant risk of incidents of forced labour or compulsory labour ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-10", dr: "SBM-3", paragraph: "14 g (i) ", relatedAr: "", name: "Information about type of operations at significant risk of incidents of child labour ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-11", dr: "SBM-3", paragraph: "14 g (ii) ", relatedAr: "", name: "Information about countries or geographic areas with operations considered at significant risk of incidents of child labour ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-12", dr: "SBM-3", paragraph: "15", relatedAr: "AR 8", name: "Disclosure of how understanding of people in its own workforce / value chain workers with particular characteristics, working in particular contexts, or undertaking particular activities may be at greater risk of harm has been developed ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-13", dr: "SBM-3", paragraph: "16", relatedAr: "AR 9", name: "Disclosure of which of material risks and opportunities arising from impacts and dependencies on poeple in its own workforce  relate to specific groups of people", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-14", dr: "S1-1", paragraph: "19", relatedAr: "", name: "Policies to manage material impacts, risks and opportunities related to its own workforce [see ESRS 2 MDR-P]", dataType: "MDR-P", status: "bg-green-500" },
    { esrsId: "S1-15", dr: "S1-1", paragraph: "19", relatedAr: "", name: "Policies to manage material impacts, risks and opportunities related to own workforce, including for specific groups within workforce or all own workforce", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-16", dr: "S1-1", paragraph: "AR10", relatedAr: "", name: "Disclosure of explanations of significant changes to policies adopted during reporting year ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-17", dr: "S1-1", paragraph: "20", relatedAr: "", name: "Description of relevant human rights policy commitments relevant to own workforce", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-18", dr: "S1-1", paragraph: "20a", relatedAr: "", name: "Disclosure of general approach in relation to respect for human rights including labour rights, of people in its own workforce", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-19", dr: "S1-1", paragraph: "20b", relatedAr: "", name: "Disclosure of general approach in relation to engagement with people in its own workforce", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-20", dr: "S1-1", paragraph: "20c", relatedAr: "", name: "Disclosure of general approach in relation to measures to provide and (or) enable remedy for human rights impacts ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-21", dr: "S1-1", paragraph: "21", relatedAr: "AR 12", name: "Disclosure of whether and how policies are aligned with relevant internationally recognised instruments ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-22", dr: "S1-1", paragraph: "22", relatedAr: "", name: "Policies explicitly address trafficking in human beings, forced labour or compulsory labour and child labour", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-23", dr: "S1-1", paragraph: "23", relatedAr: "", name: "Workplace accident prevention policy or management system is in place", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-24", dr: "S1-1", paragraph: "24a", relatedAr: "", name: "Specific policies aimed at elimination of discrimination are in place", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-25", dr: "S1-1", paragraph: "24b", relatedAr: "AR 15 - AR 16 ", name: "Grounds for discrimination are specifically covered in policy", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-26", dr: "S1-1", paragraph: "24c", relatedAr: "", name: "Disclosure of specific policy commitments related to inclusion and (or) positive action for people from groups at particular risk of vulnerability in own workforce ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-27", dr: "S1-1", paragraph: "24d", relatedAr: "", name: "Disclosure of whether and how policies are implemented through specific procedures to ensure discrimination is prevented, mitigated and acted upon once detected, as well as to advance diversity and inclusion ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-28", dr: "S1-1", paragraph: "AR 14", relatedAr: "", name: "Disclosure on an illustration of the types of communication of its policies to those individuals, group of individuals or entities for whom they are relevant", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-29", dr: "S1-1", paragraph: "AR 17 a)", relatedAr: "", name: "Policies and procedures which make qualifications, skills and experience the basis for the recruitment, placement, training and advancement are in place or planned", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-30", dr: "S1-1", paragraph: "AR 17 b)", relatedAr: "", name: "Has or planning to assign responsibility at top management level for equal treatment and opportunities in employment, issue clear company-wide policies and procedures to guide equal employment practices, and link advancement to desired performance in this area", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-31", dr: "S1-1", paragraph: "AR 17 c)", relatedAr: "", name: "Staff training on non-discrimination policies and practices are in planned or in place", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-32", dr: "S1-1", paragraph: "AR 17 d)", relatedAr: "", name: "Adjustments to the physical environment to ensure health and safety for workers, customers and other visitors with disabilities are planned or in place", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-33", dr: "S1-1", paragraph: "AR 17 e)", relatedAr: "", name: "Plans to evaluate or has evaluated whether a there is a risk that job requirements have been defined in a way that would systematically disadvantage certain groups", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-34", dr: "S1-1", paragraph: "AR 17 f)", relatedAr: "", name: "Planing to keep or keeping an up-to-date records on recruitment, training and promotion that provide a transparent view of opportunities for employees and their progression", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-35", dr: "S1-1", paragraph: "AR 17 g)", relatedAr: "", name: "Has put in place or plans to put in place grievance procedures to address complaints, handle appeals and provide recourse for employees when discrimination is identified, and is alert to formal structures and informal cultural issues that can prevent employees from raising concerns and grievances", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-36", dr: "S1-1", paragraph: "AR 17 h)", relatedAr: "", name: "Have or plans to have programs to promote access to skills development. ", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-37", dr: "", paragraph: "62", relatedAr: "", name: "Disclosures to be reported in case the undertaking has not adopted policies", dataType: "", status: "bg-green-500" },
    { esrsId: "S1-38", dr: "S1-2", paragraph: "27", relatedAr: "AR 21, AR 23-24", name: "Disclosure of whether and how perspectives of own workforce  inform decisions or activities aimed at managing actual and potential  impacts ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-39", dr: "S1-2", paragraph: "27a", relatedAr: "", name: "Engagement occurs with own workforce  or their representatives", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-40", dr: "S1-2", paragraph: "27b", relatedAr: "AR 19", name: "Disclosure of stage at which engagement occurs, type of engagement and frequency of engagement ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-41", dr: "S1-2", paragraph: "27c", relatedAr: "AR 18-19", name: "Disclosure of function and most senior role within undertaking that has operational responsibility for ensuring that engagement happens and that results inform undertakingâ€™s approach ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-42", dr: "S1-2", paragraph: "27d", relatedAr: "AR 20", name: "Disclosure of Global Framework Agreement or other agreements related to respect of human rights of workers ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-43", dr: "S1-2", paragraph: "27e", relatedAr: "", name: "Disclosure of how effectiveness of engagement with its own workforce  is assessed ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-44", dr: "S1-2", paragraph: "28", relatedAr: "", name: "Disclosure of steps taken to gain insight into perspectives of people in its own workforce that may be particularly vulnerable to impacts and (or) marginalised ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-45", dr: "S1-2", paragraph: "29", relatedAr: "", name: "Statement in case the undertaking has not adopted a general process to engage with its own workforce", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-46", dr: "S1-2", paragraph: "29", relatedAr: "", name: "Disclosure of timeframe for adoption of general process to engage with its own workforce in case the undertaking has not adopted a general process for engagement", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-47", dr: "S1-2", paragraph: "AR 25 a", relatedAr: "", name: "Disclosure of how undertaking engages with at-risk or persons in vulnerable situations", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-48", dr: "S1-2", paragraph: "AR 25 b", relatedAr: "", name: "Disclosure of how potential barriers to engagement with people in its workforce are taken into account ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-49", dr: "S1-2", paragraph: "AR 25 c", relatedAr: "", name: "Disclosure of how people in its workforce are provided with information that is understandable and accessible through appropriate communication channels ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-50", dr: "S1-2", paragraph: "AR 25 d", relatedAr: "", name: "Disclosure of any conflicting interests that have arisen among different workers and how these conflicting interests have been resolved ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-51", dr: "S1-2", paragraph: "AR 25 e", relatedAr: "", name: "Disclosure of how undertaking seeks to respect human rights of all stakeholders engaged ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-52", dr: "S1-2", paragraph: "AR 26", relatedAr: "", name: "Information about effectiveness of processes for engaging with ist own workforce from previous reporting periods ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-53", dr: "S1-3", paragraph: "32a", relatedAr: "AR 27", name: "Disclosure of general approach to and processes for providing or contributing to remedy where undertaking has caused or contributed to a material negative impact on people in ist own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-54", dr: "S1-3", paragraph: "32b", relatedAr: "AR 28", name: "Disclosure of specific channels in place for ist own workforce to raise concerns or needs directly with undertaking and have them addressed ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-55", dr: "S1-3", paragraph: "AR 29", relatedAr: "", name: "Third-party mechanisms are accessible to all own workforce", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-56", dr: "S1-3", paragraph: "AR 30", relatedAr: "", name: "Disclosure of how own workforce and their workers' representatives are able to access channels at level of undertaking they are employed by or contracted to work for ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-57", dr: "S1-3", paragraph: "32c", relatedAr: "", name: "Grievance or complaints handling mechanisms related to employee matters exist", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-58", dr: "S1-3", paragraph: "32d", relatedAr: "", name: "Disclosure of processes through which undertaking supports or requires availability of channels ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-59", dr: "S1-3", paragraph: "32e", relatedAr: "AR 32", name: "Disclosure of how issues raised and addressed are tracked and monitored and how effectiveness of channels is ensured ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-60", dr: "S1-3", paragraph: "33", relatedAr: "AR 31", name: "Disclosure of whether and how it is assessed that its own workforce is aware of and trust structures or processes as way to raise their concerns or needs and have them addressed ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-61", dr: "S1-3", paragraph: "33", relatedAr: "", name: "Policies regarding protection against retaliation for individuals that use channels to raise concerns or needs are in place", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-62", dr: "S1-3", paragraph: "34", relatedAr: "", name: "Statement in case the undertaking has not adopted a channel for raising concerns ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-63", dr: "S1-3", paragraph: "34", relatedAr: "", name: "Disclosure of timeframe for channel for raising concerns to be in place", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-64", dr: "S1-4", paragraph: "37", relatedAr: "", name: "Action plans and resources to manage its material impacts, risks, and opportunities related to its own workforce [see ESRS 2 - MDR-A]", dataType: "MDR-A", status: "bg-green-500" },
    { esrsId: "S1-65", dr: "S1-4", paragraph: "38a", relatedAr: "AR 42", name: "Description of action taken, planned or underway to prevent or mitigate negative impacts on own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-66", dr: "S1-4", paragraph: "38b", relatedAr: "", name: "Disclosure on whether and how action has been taken to provide or enable remedy in relation to actual material impact", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-67", dr: "S1-4", paragraph: "38c", relatedAr: "AR 42", name: "Description of additional initiatives or actions with primary purpose of delivering positive impacts for own workforce", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-68", dr: "S1-4", paragraph: "38d", relatedAr: "AR 38-AR 39", name: "Description of how effectiveness of actions and initiatives in delivering outcomes for own workforce is tracked and assessed ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-69", dr: "S1-4", paragraph: "39", relatedAr: "AR 34", name: "Description of process through which it identifies what action is needed and appropriate in response to particular actual or potential negative impact on own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-70", dr: "S1-4", paragraph: "40a", relatedAr: "AR 44-45, AR 47", name: "Description of what action is planned or underway to mitigate material risks arising from impacts and dependencies on own workforce  and how effectiveness is tracked ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-71", dr: "S1-4", paragraph: "40b", relatedAr: "", name: "Description of what action is planned or underway to pursue material opportunities in relation to own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-72", dr: "S1-4", paragraph: "41", relatedAr: "AR 37", name: "Disclosure of whether and how it is ensured that own practices do not cause or contribute to material negative impacts on own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-73", dr: "S1-4", paragraph: "43", relatedAr: "", name: "Disclosure of resources are allocated to the management of material impacts", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-74", dr: "S1-4", paragraph: "AR 33 a", relatedAr: "", name: "Disclosure of general and specific approaches to addressing material negative impacts ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-75", dr: "S1-4", paragraph: "AR 33 b", relatedAr: "", name: "Disclosure of initiatives aimed at contributing to additional material positive impacts ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-76", dr: "S1-4", paragraph: "AR 33 c", relatedAr: "", name: "Disclosure of how far undertaking has progressed in efforts during reporting period ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-77", dr: "S1-4", paragraph: "AR 33 d", relatedAr: "", name: "Disclosure of aims for continued improvement ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-78", dr: "S1-4", paragraph: "AR 35", relatedAr: "", name: "Disclosure of whether and how undertaking seeks to use leverage with relevant business relationships to manage material negative impacts affecting own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-79", dr: "S1-4", paragraph: "AR 36", relatedAr: "", name: "Disclosure of how the initiative, and its own involvement, is aiming to address the material impact concerned", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-80", dr: "S1-4", paragraph: "AR 40 a", relatedAr: "", name: "Disclosure of whether and how workers and workers' representatives play role in decisions regarding design and implementation of programmes or processes whose primary aim is to deliver positive impacts for workers ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-81", dr: "S1-4", paragraph: "AR 40 b", relatedAr: "", name: "Information about intended or achieved positive outcomes of programmes or processes for own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-82", dr: "S1-4", paragraph: "AR 41", relatedAr: "", name: "Initiatives or processes whose primary aim is to deliver positive impacts for own workforce  are designed also to support achievement of one or more of Sustainable Development Goals", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-83", dr: "S1-4", paragraph: "AR 43", relatedAr: "", name: "Information about measures taken to mitigate negative impacts on workers that arise from transition to greener, climate-neutral economy ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-84", dr: "S1-4", paragraph: "AR 48", relatedAr: "", name: "Description of internal functions that are involved in managing impacts and types of action taken by internal functions to address negative and advance positive impacts ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-85", dr: "", paragraph: "62", relatedAr: "", name: "Disclosures to be reported if the undertaking has not adopted actions", dataType: "", status: "bg-green-500" },
    { esrsId: "S1-86", dr: "S1-5", paragraph: "46", relatedAr: "AR 50-AR52", name: "Targets set to manage material impacts, risks and opportunities related to own workforce [see ESRS 2 - MDR-T]", dataType: "MDR-T", status: "bg-green-500" },
    { esrsId: "S1-87", dr: "S1-5", paragraph: "47a", relatedAr: "", name: "Disclosure of whether and how own workforce or workforce' representatives were engaged directly in setting targets ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-88", dr: "S1-5", paragraph: "47b", relatedAr: "", name: "Disclosure of whether and how own workforce or workforce' representatives were engaged directly in tracking performance against targets ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-89", dr: "S1-5", paragraph: "47c", relatedAr: "", name: "Disclosure of whether and how own workforce or workforce' representatives were engaged directly in identifying lessons or improvements as result of undertakings performance ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-90", dr: "S1-5", paragraph: "AR 49 a", relatedAr: "", name: "Disclosure of intended outcomes to be achieved in lives of people in its own workforce  ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-91", dr: "S1-5", paragraph: "AR 49 b", relatedAr: "", name: "Information about stability over time of target in terms of definitions and methodologies to enable comparability ", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-92", dr: "S1-5", paragraph: "AR 49 c", relatedAr: "", name: "Disclosure of references to standards or commitments which targets are based on", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-93", dr: "", paragraph: "81", relatedAr: "", name: "Disclosures to be reported if the undertaking has not adopted targets", dataType: "", status: "bg-green-500" },
    { esrsId: "S1-94", dr: "S1-6", paragraph: "50a", relatedAr: "", name: "Characteristics of undertaking's employees - number of employees by gender [table]", dataType: "Table A", status: "bg-green-500" },
    { esrsId: "S1-95", dr: "S1-6", paragraph: "50a", relatedAr: "AR 57", name: "Number of employees (head count)", dataType: "Table A/Decimal", status: "bg-green-500" },
    { esrsId: "S1-96", dr: "S1-6", paragraph: "50a", relatedAr: "AR 57", name: "Average number of employees (head count)", dataType: "Table A/Decimal", status: "bg-green-500" },
    { esrsId: "S1-97", dr: "S1-6", paragraph: "50a", relatedAr: "", name: "Characteristics of undertaking's employees - number of employees in countries with 50 or more employees representing at least 10% of total number of employees [table]", dataType: "Table B", status: "bg-green-500" },
    { esrsId: "S1-98", dr: "S1-6", paragraph: "50a", relatedAr: "AR 57", name: "Number of employees in countries with 50 or more employees representing at least 10% of total number of employees", dataType: "Table B/Decimal", status: "bg-green-500" },
    { esrsId: "S1-99", dr: "S1-6", paragraph: "50a", relatedAr: "AR 57", name: "Average number of employees in countries with 50 or more employees representing at least 10% of total number of employees", dataType: "Table B/Decimal", status: "bg-green-500" },
    { esrsId: "S1-100", dr: "S1-6", paragraph: "50b", relatedAr: "", name: "Characteristics of undertaking's employees - information on employees by contract type and gender  [table]", dataType: "Table C", status: "bg-green-500" },
    { esrsId: "S1-101", dr: "S1-6", paragraph: "51", relatedAr: "", name: "Characteristics of undertaking's employees - information on employees by region [table]", dataType: "Table C", status: "bg-green-500" },
    { esrsId: "S1-102", dr: "S1-6", paragraph: "50b + 51", relatedAr: "", name: "Number of employees (head count or full-time equivalent)", dataType: "Table C/Decimal", status: "bg-green-500" },
    { esrsId: "S1-103", dr: "S1-6", paragraph: "50b + 51", relatedAr: "", name: "Average number of employees (head count or full-time equivalent)", dataType: "Table C/Decimal", status: "bg-green-500" },
    { esrsId: "S1-104", dr: "S1-6", paragraph: "50c", relatedAr: "AR 59", name: "Number of employee who have left undertaking	", dataType: "Decimal", status: "bg-green-500" },
    { esrsId: "S1-105", dr: "S1-6", paragraph: "50c", relatedAr: "", name: "Percentage of employee turnover", dataType: "Percent", status: "bg-green-500" },
    { esrsId: "S1-106", dr: "S1-6", paragraph: "50d", relatedAr: "AR 60", name: "Description of methodologies and assumptions used to compile data (employees) ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-107", dr: "S1-6", paragraph: "50 d (i) ", relatedAr: "", name: "Employees numbers are reported in head count or full-time equivalent", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-108", dr: "S1-6", paragraph: "50 d (ii) ", relatedAr: "", name: "Employees numbers are reported at end of reporting period/average/other methodology", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-109", dr: "S1-6", paragraph: "50e", relatedAr: "AR 58", name: "Disclosure of contextual information necessary to understand data (employees) ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-110", dr: "S1-6", paragraph: "50f", relatedAr: "", name: "Disclosure of cross-reference of information reported under paragragph 50 (a) to most representative number in ficial statements ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-111", dr: "S1-6", paragraph: "52", relatedAr: "", name: "Further detailed breakdown by gender and by region [table]", dataType: "Table D", status: "bg-green-500" },
    { esrsId: "S1-112", dr: "S1-6", paragraph: "52 a", relatedAr: "", name: "Number of full-time employees by head count or full time equivalent", dataType: "Table D Decimal/Integer", status: "bg-green-500" },
    { esrsId: "S1-113", dr: "S1-6", paragraph: "52 b", relatedAr: "", name: "Number of part-time employees by head count or full time equivalent", dataType: "Table D Decimal/Integer", status: "bg-green-500" },
    { esrsId: "S1-114", dr: "S1-7", paragraph: "55 a", relatedAr: "AR 61", name: "Number of non-employees in own workforce", dataType: "Decimal", status: "bg-green-500" },
    { esrsId: "S1-115", dr: "S1-7", paragraph: "55 a", relatedAr: "", name: "Number of non-employees in own workforce - self-employed people", dataType: "Decimal", status: "bg-green-500" },
    { esrsId: "S1-116", dr: "S1-7", paragraph: "55 a", relatedAr: "", name: "Number of non-employees in own workforce - people provided by undertakings primarily engaged in employment activities", dataType: "Decimal", status: "bg-green-500" },
    { esrsId: "S1-117", dr: "S1-7", paragraph: "56", relatedAr: "AR 62", name: "Disclosure of the most common types of non-employees (for example, self-employed people, people provided by undertakings primarily engaged in employment activities, and other types relevant to the undertaking), their relationship with the undertaking, and the type of work that they perform.", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-118", dr: "S1-7", paragraph: "55 b", relatedAr: "", name: "Description of methodologies and assumptions used to compile data (non-employees) ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-119", dr: "S1-7", paragraph: "55 b (i)", relatedAr: "", name: "Non-employees numbers are reported in head count/full time equivalent", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-120", dr: "S1-7", paragraph: "55 b (ii)", relatedAr: "", name: "Non-employees numbers are reported at end of reporting period/average/other methodology", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-121", dr: "S1-7", paragraph: "55c", relatedAr: "AR 64- AR 65", name: "Disclosure of contextual information necessary to understand data (non-employee workers) ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-122", dr: "S1-7", paragraph: "57", relatedAr: "AR 63", name: "Description of basis of preparation of non-employees estimated number ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-123", dr: "S1-8", paragraph: "60 a", relatedAr: "AR 66", name: "Percentage of total employees covered by collective bargaining agreements", dataType: "Percent", status: "bg-green-500" },
    { esrsId: "S1-124", dr: "S1-8", paragraph: "60 b", relatedAr: "", name: "Percentage of its employees covered by collective bargaining agreements are within coverage rate by country (in the EEA)", dataType: "Table/Percent", status: "bg-green-500" },
    { esrsId: "S1-125", dr: "S1-8", paragraph: "60 c", relatedAr: "", name: "Percentage of own employees covered by collective bargaining agreements (outside EEA) by region", dataType: "Table/Percent", status: "bg-green-500" },
    { esrsId: "S1-126", dr: "S1-8", paragraph: "61", relatedAr: "", name: "Working conditions and terms of employment for employees not covered by collective bargaining agreements are determined based on collective bargaining agreements that cover other employees or based on collective bargaining agreements from other undertakings", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-127", dr: "S1-8", paragraph: "62", relatedAr: "", name: "Description of extent to which working conditions and terms of employment of non-employees in own workforce are determined or influenced by collective bargaining agreements ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-128", dr: "S1-8", paragraph: "63a", relatedAr: "AR 69", name: "Percentage of employees in country (EEA) covered by workers' representatives", dataType: "Percent", status: "bg-green-500" },
    { esrsId: "S1-129", dr: "S1-8", paragraph: "63b", relatedAr: "", name: "Disclosure of existence of any agreement with employees for representation by European Works Council (EWC), Societas Europaea (SE) Works Council, or Societas Cooperativa Europaea (SCE) Works Council ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-130", dr: "S1-8", paragraph: "AR 70", relatedAr: "", name: "Own workforce in region (non-EEA) covered by collective bargaining agreements by coverage rate and by region", dataType: "Table /Semi-Narrative", status: "bg-green-500" },
    { esrsId: "S1-131", dr: "S1-9", paragraph: "66a", relatedAr: "", name: "Number of employees (head count) at top management level", dataType: "Integer", status: "bg-green-500" },
    { esrsId: "S1-132", dr: "S1-9", paragraph: "66a", relatedAr: "", name: "Percentage of employees at top management level", dataType: "Percent", status: "bg-green-500" },
    { esrsId: "S1-133", dr: "S1-9", paragraph: "66b", relatedAr: "", name: "Number of employees (head count) under 30 years old", dataType: "Integer", status: "bg-green-500" },
    { esrsId: "S1-134", dr: "S1-9", paragraph: "66b", relatedAr: "", name: "Percentage of employees under 30 years old", dataType: "Percent", status: "bg-green-500" },
    { esrsId: "S1-135", dr: "S1-9", paragraph: "66b", relatedAr: "", name: "Number of employees (head count) between 30 and 50 years old", dataType: "Integer", status: "bg-green-500" },
    { esrsId: "S1-136", dr: "S1-9", paragraph: "66b", relatedAr: "", name: "Percentage of employees between 30 and 50 years old", dataType: "Percent", status: "bg-green-500" },
    { esrsId: "S1-137", dr: "S1-9", paragraph: "66b", relatedAr: "", name: "Number of employees (head count) over 50 years old", dataType: "Integer", status: "bg-green-500" },
    { esrsId: "S1-138", dr: "S1-9", paragraph: "66b", relatedAr: "", name: "Percentage of employees over 50 years old", dataType: "Percent", status: "bg-green-500" },
    { esrsId: "S1-139", dr: "S1-9", paragraph: "AR 71", relatedAr: "", name: "Disclosure of own definition of top management used ", dataType: "narrative", status: "bg-green-500" },
    { esrsId: "S1-140", dr: "S1-10", paragraph: "69", relatedAr: "AR 72- AR 74", name: "All employees are paid adequate wage, in line with applicable benchmarks", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-141", dr: "S1-10", paragraph: "70", relatedAr: "", name: "Adequate wages by country [table]", dataType: "Table E/numerical", status: "bg-green-500" },
    { esrsId: "S1-142", dr: "S1-10", paragraph: "70", relatedAr: "", name: "Percentage of  employees paid below the applicable adequate wage benchmark", dataType: "Table E/Percent", status: "bg-green-500" },
    { esrsId: "S1-143", dr: "S1-10", paragraph: "71", relatedAr: "", name: "Percentage of non-employees paid below adequate wage", dataType: "Table E/Percent", status: "bg-green-500" },
    { esrsId: "S1-144", dr: "S1-11", paragraph: "74 a", relatedAr: "", name: "All employees in own workforce are covered by social protection, through public programs or through benefits offered, against loss of income due to sickness", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-145", dr: "S1-11", paragraph: "74 b", relatedAr: "", name: "All employees in own workforce are covered by social protection, through public programs or through benefits offered, against loss of income due to unemployment starting from when own worker is working for undertaking", dataType: "semi-narrative", status: "bg-green-500" },
    { esrsId: "S1-146", dr: "S1-11", paragraph: "74 c", relatedAr: "", name: "All employees in own workforce are covered by social protection, through public programs or through benefits offered, against loss of income due to employment injury and acquired disability", dataType: "semi-narrative", status: "bg-yellow-500" },
    { esrsId: "S1-147", dr: "S1-11", paragraph: "74 d", relatedAr: "", name: "All employees in own workforce are covered by social protection, through public programs or through benefits offered, against loss of income due to parental leave", dataType: "semi-narrative", status: "bg-yellow-500" },
    { esrsId: "S1-148", dr: "S1-11", paragraph: "74 e", relatedAr: "", name: "All employees in own workforce are covered by social protection, through public programs or through benefits offered, against loss of income due to retirement", dataType: "semi-narrative", status: "bg-yellow-500" },
    { esrsId: "S1-149", dr: "S1-11", paragraph: "75", relatedAr: "AR 75", name: "Social protection employees by country [table] by types of events and type of employees [including non employees]", dataType: "Table", status: "bg-yellow-500" },
    { esrsId: "S1-150", dr: "S1-11", paragraph: "75", relatedAr: "", name: "Disclosure of types of employees who are not covered by social protection, through public programs or through benefits offered, against loss of income due to sickness ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-151", dr: "S1-11", paragraph: "75", relatedAr: "", name: "Disclosure of types of employees who are not covered by social protection, through public programs or through benefits offered, against loss of income due to unemployment starting from when own worker is working for undertaking ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-152", dr: "S1-11", paragraph: "75", relatedAr: "", name: "Disclosure of types of employees who are not covered by social protection, through public programs or through benefits offered, against loss of income due to employment injury and acquired disability ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-153", dr: "S1-11", paragraph: "75", relatedAr: "", name: "Disclosure of types of employees who are not covered by social protection, through public programs or through benefits offered, against loss of income due to maternity leave ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-154", dr: "S1-11", paragraph: "75", relatedAr: "", name: "Disclosure of types of employees who are not covered by social protection, through public programs or through benefits offered, against loss of income due to retirement ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-155", dr: "S1-12", paragraph: "79", relatedAr: "", name: "Percentage of persons with disabilities amongst employees subject to legal restrictions on collection of data", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-156", dr: "S1-12", paragraph: "80", relatedAr: "", name: "Percentage of employees with disabilities in own workforce breakdown by gender [table]", dataType: "Table/numerical", status: "bg-yellow-500" },
    { esrsId: "S1-157", dr: "S1-12", paragraph: "AR 76", relatedAr: "", name: "Disclosure of contextual information necessary to understand data and how data has been compiled (persons with disabilities)) ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-158", dr: "S1-13", paragraph: "83 a ", relatedAr: "AR 77", name: "Training and skills development indicators gender [table]", dataType: "Table F", status: "bg-yellow-500" },
    { esrsId: "S1-159", dr: "S1-13", paragraph: "83 a ", relatedAr: "AR 77", name: "Percentage of employees that participated in regular performance and career development reviews", dataType: "Table F/Percent", status: "bg-yellow-500" },
    { esrsId: "S1-160", dr: "S1-13", paragraph: "83 b", relatedAr: "AR 78", name: "Average number of training hours  by gender [table]", dataType: "Table G", status: "bg-yellow-500" },
    { esrsId: "S1-161", dr: "S1-13", paragraph: "83 b", relatedAr: "AR 78", name: "Average number of training hours per person for employees", dataType: "Table G/Decimal", status: "bg-yellow-500" },
    { esrsId: "S1-162", dr: "S1-13", paragraph: "84", relatedAr: "AR 79", name: "Percentage of employees that participated in regular performance and career development reviews by employee category [table]", dataType: "Table G/percentage", status: "bg-yellow-500" },
    { esrsId: "S1-163", dr: "S1-13", paragraph: "84", relatedAr: "AR 79", name: "Average number of employees that participated in regular performance and career development reviews by employee category", dataType: "Table G/Decimal", status: "bg-yellow-500" },
    { esrsId: "S1-164", dr: "S1-13", paragraph: "85", relatedAr: "", name: "Percentage of non-employees that participated in regular performance and career development reviews", dataType: "Table G/Percent", status: "bg-yellow-500" },
    { esrsId: "S1-165", dr: "S1-14", paragraph: "88 a", relatedAr: "AR 80", name: "Percentage of people in its own workforce who are covered by health and safety management system based on legal requirements and (or) recognised standards or guidelines", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-166", dr: "S1-14", paragraph: "88b", relatedAr: "AR 89-91", name: "Number of fatalities in own workforce as result of work-related injuries and work-related ill health", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-167", dr: "S1-14", paragraph: "88b", relatedAr: "AR 89-91", name: "Number of fatalities as result of work-related injuries and work-related ill health of other workers working on undertaking's sites", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-168", dr: "S1-14", paragraph: "88c", relatedAr: "", name: "Number of recordable work-related accidents for own workforce", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-169", dr: "S1-14", paragraph: "88c", relatedAr: "", name: "Rate of recordable work-related accidents for own workforce", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-170", dr: "S1-14", paragraph: "88d", relatedAr: "", name: "Number of cases of recordable work-related ill health of employees", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-171", dr: "S1-14", paragraph: "88e", relatedAr: "AR 89-91, AR 95", name: "Number of days lost to work-related injuries and fatalities from work-related accidents, work-related ill health and fatalities from ill health realted to employees", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-172", dr: "S1-14", paragraph: "89", relatedAr: "", name: "Number of cases of recordable work-related ill health of non-employees", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-173", dr: "S1-14", paragraph: "89", relatedAr: "", name: "Number of days lost to work-related injuries and fatalities from work-related accidents, work-related ill health and fatalities from ill health realted to non-employees", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-174", dr: "S1-14", paragraph: "90", relatedAr: "", name: "Percentage of own workforce who are covered by health and safety management system based on legal requirements and (or) recognised standards or guidelines and which has been internally audited and (or) audited or certified by external party", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-175", dr: "S1-14", paragraph: "AR 81", relatedAr: "", name: "Description of underlying standards for internal audit or external certification of health and safety management system ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-176", dr: "S1-14", paragraph: "AR 82", relatedAr: "", name: "Number of fatalities in own workforce as result of work-related injuries", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-177", dr: "S1-14", paragraph: "AR 82", relatedAr: "", name: "Number of fatalities in own workforce as result of work-related ill health", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-178", dr: "S1-14", paragraph: "AR 82", relatedAr: "", name: "Number of fatalities as result of work-related injuries of other workers working on undertaking's sites", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-179", dr: "S1-14", paragraph: "AR 82", relatedAr: "", name: "Number of fatalities as result of work-related ill health of other workers working on undertaking's sites", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-180", dr: "S1-14", paragraph: "AR 94", relatedAr: "", name: "Number of cases of recordable work-related ill health detected among former own workforce", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-181", dr: "S1-15", paragraph: "93 a", relatedAr: "AR 96-AR 97", name: "Percentage of employees entitled to take family-related leave", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-182", dr: "S1-15", paragraph: "93 b", relatedAr: "", name: "Percentage of entitled employees that took family-related leave", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-183", dr: "S1-15", paragraph: "93 b", relatedAr: "", name: "Percentage of entitled employees that took family-related leave by gender [table]", dataType: "Table/numerical", status: "bg-yellow-500" },
    { esrsId: "S1-184", dr: "S1-15", paragraph: "94", relatedAr: "", name: "All employees are entitled to family-related leaves through social policy and (or) collective bargaining agreements", dataType: "semi-narrative", status: "bg-yellow-500" },
    { esrsId: "S1-185", dr: "S1-16", paragraph: "97 a ", relatedAr: "AR 98-AR 99-AR 100", name: "Gender pay gap [table]", dataType: "Table H", status: "bg-yellow-500" },
    { esrsId: "S1-186", dr: "S1-16", paragraph: "97 a ", relatedAr: "AR 98-AR 99-AR 100", name: "Gender pay gap", dataType: "Table H/Percent", status: "bg-yellow-500" },
    { esrsId: "S1-187", dr: "S1-16", paragraph: "97 b", relatedAr: "AR 101", name: "Annual total remuneration ratio", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-188", dr: "S1-16", paragraph: "97 c", relatedAr: "AR 102", name: "Disclosure of contextual information necessary to understand data, how data has been compiled and other changes to underlying data that are to be considered ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-189", dr: "S1-16", paragraph: "98", relatedAr: "", name: "Gender pay gap breakdown by employee category and/or country/segment [table]", dataType: "Table/numerical", status: "bg-yellow-500" },
    { esrsId: "S1-190", dr: "S1-16", paragraph: "98", relatedAr: "", name: "Gender pay gap breakdown by ordinary basic salary and complementary/variable components", dataType: "Table/numerical", status: "bg-yellow-500" },
    { esrsId: "S1-191", dr: "S1-16", paragraph: "99", relatedAr: "", name: "Remuneration ratio adjusted for purchasing power differences between countries", dataType: "Percent", status: "bg-yellow-500" },
    { esrsId: "S1-192", dr: "S1-16", paragraph: "99", relatedAr: "", name: "Description of methodology used for calculation of remuneration ratio adjusted for purchasing power differences between countries ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-193", dr: "S1-17", paragraph: "103 a", relatedAr: "", name: "Number of incidents of discrimination [table]", dataType: "Table I", status: "bg-yellow-500" },
    { esrsId: "S1-194", dr: "S1-17", paragraph: "103 a ", relatedAr: "AR 103- AR 106", name: "Number of incidents of discrimination", dataType: "Table I/Integer", status: "bg-yellow-500" },
    { esrsId: "S1-195", dr: "S1-17", paragraph: "103 b", relatedAr: "AR 103- AR 106", name: "Number of complaints filed through channels for people in own workforce to raise concerns", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-196", dr: "S1-17", paragraph: "103 b", relatedAr: "AR 103- AR 106", name: "Number of complaints filed to National Contact Points for OECD Multinational Enterprises", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-197", dr: "S1-17", paragraph: "103 c", relatedAr: "AR 103- AR 106", name: "Amount of material fines, penalties, and compensation for damages as result of violations regarding social and human rights factors", dataType: "Monetary", status: "bg-yellow-500" },
    { esrsId: "S1-198", dr: "S1-17", paragraph: "103 c ", relatedAr: "AR 103- AR 106", name: "Information about reconciliation of material fines, penalties, and compensation for damages as result of violations regarding social and human rights factors with most relevant amount presented in ficial statements ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-199", dr: "S1-17", paragraph: "103 d", relatedAr: "AR 103- AR 106", name: "Disclosure of contextual information necessary to understand data and how data has been compiled (work-related grievances, incidents and complaints related to social and human rights matters) ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-200", dr: "S1-17", paragraph: "104 a", relatedAr: "AR 105", name: "Number of severe human rights issues and incidents connected to own workforce", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-201", dr: "S1-17", paragraph: "104 a", relatedAr: "AR 105", name: "Number of severe human rights issues and incidents connected to own workforce that are cases of non respect of UN Guiding Principles and OECD Guidelines for Multinational Enterprises", dataType: "Integer", status: "bg-yellow-500" },
    { esrsId: "S1-202", dr: "S1-17", paragraph: "104 a", relatedAr: "AR 105", name: "No severe human rights issues and incidents connected to own workforce have occurred", dataType: "semi-narrative", status: "bg-yellow-500" },
    { esrsId: "S1-203", dr: "S1-17", paragraph: "104 b", relatedAr: "AR 103- AR 106", name: "Amount of material fines, penalties, and compensation for severe human rights issues and incidents connected to own workforce", dataType: "Monetary", status: "bg-yellow-500" },
    { esrsId: "S1-204", dr: "S1-17", paragraph: "104 b", relatedAr: "AR 103- AR 106", name: "Information about reconciliation of amount of material fines, penalties, and compensation for severe human rights issues and incidents connected to own workforce with most relevant amount presented in ficial statements ", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-205", dr: "S1-17", paragraph: "AR 103", relatedAr: "", name: "Disclosure of the status of incidents and/or complaints and actions taken", dataType: "narrative", status: "bg-yellow-500" },
    { esrsId: "S1-206", dr: "S1-17", paragraph: "AR 106", relatedAr: "", name: "Number of severe human rights cases where undertaking played role securing remedy for those affected", dataType: "Integer", status: "bg-yellow-500" }
  ];

export default function Component() {
  return (
    <div className="border rounded overflow-hidden">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="w-[100px]">ESRS ID (S1)</TableHead>
            <TableHead className="w-[100px]">DR (S1-5)</TableHead>
            <TableHead>Paragraph</TableHead>
            <TableHead>Related AR Name</TableHead>
            <TableHead>Name</TableHead>
            <TableHead>Data Type</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {esrsS1Data.map((data, index) => (
            <TableRow key={index} className={index % 2 === 0 ? "bg-gray-100 dark:bg-gray-800" : ""}>
              <TableCell className="font-medium">{data.esrsId}</TableCell>
              <TableCell>{data.dr}</TableCell>
              <TableCell>{data.paragraph}</TableCell>
              <TableCell>{data.relatedAr}</TableCell>
              <TableCell>{data.name}</TableCell>
              <TableCell>{data.dataType}</TableCell>
              <TableCell>
                <div className={"h-3 w-3 rounded-full " + data.status} />
              </TableCell>
              <TableCell>
                <Link href="/dev/reporting/frameworks/esrss1/s1-23">
                <Button variant="link" size="sm">
                  Edit
                </Button>
                </Link>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}
